### ISSUE TITLE
Create Helm Repo

### ISSUE THREAD

**Issue by CmdrSharp** [stefanvangastel/vsphere-cpi-csi-helm#14]
The lack of a Helm Repo means that installation is an extra step for non-Rancher deployments.
Hosting a Helm Repo in GitHub Pages would seem to make sense.

If you can create a new branch (maybe named gh-pages), and create a GitHub Page for that branch - I have already packaged the latest release and indexed it, so I could make a PR to that branch.
https://github.com/CmdrSharp/vsphere-cpi-csi-helm/tree/gh-pages

**Comment by stefanvangastel** [comment]
@CmdrSharp I created a gh-pages branch

**Comment by CmdrSharp** [comment]
Sweet, closing this out as we now have a fully functioning repo :) Thanks for your assistance @stefanvangastel!
